[project]
name = "kbo-occultation"
version = "0.2.0"
description = "Simulation of KBO stellar occultation diffraction patterns"
authors = [{name="eliadse"}]
license = { text = "MIT" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Astronomy",
]
dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "astropy",
    "pandas"
]

[project.optional-dependencies]
test = ["pytest"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"kbo_occultation.data" = ["**/*.txt", "**/*.dat", "**/*.fits", "**/*.csv"]

[tool.pytest.ini_options]
testpaths = ["tests/unit"]
